name: deploy-firestore
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: debug github
        run: |
          echo "repo=${{ github.repository }}"
          echo "ref=${{ github.ref }}"

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/544034667602/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: deploy-sa@recovery-engine.iam.gserviceaccount.com
          create_credentials_file: true

      - run: npm i -g firebase-tools
      - run: firebase deploy --only firestore:rules,firestore:indexes --project recovery-engine

